### ISSUE TITLE
Can not send my groestlcoins to any other wallet or exchange

### ISSUE THREAD

**Issue by robertbuerger** [Groestlcoin/grs-rush-wallet#1]
Hello there,

I was able to receive coins in the jswallet. Unfortunately I can not send them to other wallets or exchanges now.
I just get following message:
"There seems to be a problem with building the transaction. Please try again.."

Looking forward to some help.
Best
Robert

**Comment by gruve-p** [comment]
Hi!

Will check it out. In the meanwhile you can move your funds by importing your private keys:
Settings - Export Keys - Private key.

You can import it to Groestlwallet or Groestlpay

KR
Gruve

**Comment by gruve-p** [comment]
Your transaction is being rejected:
Transaction rejected by network (code -26). Reason: 64: non-mandatory-script-verify-flag (Non-canonical signature: S value is unnecessarily high)

Need some time to troubleshoot and fix. Please sweep your private key and transfer your funds elsewhere

**Comment by robertbuerger** [comment]
Hi,

thank you for your fast response.

How can I sweep my private key?
If I try to import a wallet in the Groestlwallet or Groestlpay I have to enter the 12 word passphrase.

Thank you in advance.

**Comment by gruve-p** [comment]
Install groestlwallet.
Set up your wallet by writing your 12 word passphrase and entering it.
go to menu and choose import private key

You can convert your private key to QR code here http://www.qr-code-generator.com/
go to text and paste your private key there.

**Comment by robertbuerger** [comment]
Thx it worked.

Best
Robert

**Comment by gruve-p** [comment]
Great to hear.
Issue on jswallet should be solved also now
